### ISSUE TITLE
BUG - Adding a user more than once, shows them that many times.

### ISSUE THREAD

**Issue by sandipagarwal** [standup-raven/standup-raven#39] opened 2019-05-30 12:19 UTC
**Summary**
If a user is added more than once in the standup config, s/he is shown that many times.

**Steps To Reproduce**
1. Run `/standupaddmembers @sandip.agarwal`
2. Run the above again
3. Run `/standupviewconfig `
4. See the output to have more than one entry of the above user.

**Expected behavior**
Each user should have only one entry.

**Observed Behavior**
Users added more than once, show up that many times.

**Screenshots**
<img width="812" alt="Screenshot 2019-05-30 at 5 44 07 PM" src="https://user-images.githubusercontent.com/988003/58632456-1ad7c680-8303-11e9-858e-0ce7c29770c2.png">
(See for yugank.sharma)

**Environment**
-  Mattermost version: e.g. 3.7.1
-  OS: macOS 10.14.5
-  Platform: desktop app
-  Browser (if applicable): NA
-  Platform Version: e.g. -

**Comment by harshilsharma** [comment] 2019-05-30 14:25
HI @sandipagarwal! Thanks for the bug report.

This seems to be a duplicate of #19 , which has been fixed in the latest [v1.3.0](https://github.com/standup-raven/standup-raven/releases/tag/v1.3.0) release. Can you try updating the installed version of the plugin?

**Comment by sandipagarwal** [comment] 2019-05-31 06:28
@harshilsharma - Thanks for the fix. I updated the plugin and it works. Two observations:
1. Adding a user multiple times works correctly now.
2. The old data still stays as it is. We have to add the repeated user(s) again for cleaning.

**Comment by harshilsharma** [comment] 2019-06-03 23:46
@sandipagarwal thanks for the confirmation. Closing the issue now.

**Closed by harshilsharma** 2019-06-03 23:46 UTC
Labels: bug, duplicate
