### ISSUE TITLE
BUG - timezone issue prevents plugin to start

### ISSUE THREAD

**Issue by poVoq** [standup-raven/standup-raven#28] opened 2019-05-20 09:17 UTC
**Summary**
I can't start the plugin on Mattermost team edition Docker and the error log is about a time zone issue. I tried various time zone settings.

**suspected reason**
Contrary to the Mattermost Docker install instructions I am not bridging the timezone file, as my Docker volume is in a seperate network with no access to the host system / "bridge" network.
Alternatively it could be due to running Mattermost with MySQL 5.7? 

**Error Log**
 ":"error","ts":1558342988.0937357,"caller":"mlog/log.go:172","msg":"Unable to activate plugin","plugin_id":"standup-raven","error":"unable to start plugin: standup-raven: unknown time zone Etc/UTC","errorVerbose":"unknown time zone Etc/UTC\nunable to start plugin: standup-raven\ngithub.com/mattermost/mattermost-server/plugin.(*Environment).Activate\n\t/go/src/github.com/mattermost/mattermost-server/plugin/environment.go:216\ngithub.com/mattermost/mattermost-server/app.(*App).SyncPluginsActiveState\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:95\ngithub.com/mattermost/mattermost-server/app.(*App).InitPlugins\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:126\ngithub.com/mattermost/mattermost-server/app.(*Server).RunOldAppInitalization.func6\n\t/go/src/github.com/mattermost/mattermost-server/app/server_app_adapters.go:147\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners.func1\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:35\nsync.(*Map).Range\n\t/usr/local/go/src/sync/map.go:333\ngithub.com/mattermost/mattermost-server/config.(*emitter).invokeConfigListeners\n\t/go/src/github.com/mattermost/mattermost-server/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/config.(*commonStore).set\n\t/go/src/github.com/mattermost/mattermost-server/config/common.go:80\ngithub.com/mattermost/mattermost-server/config.(*FileStore).Set\n\t/go/src/github.com/mattermost/mattermost-server/config/file.go:97\ngithub.com/mattermost/mattermost-server/app.(*Server).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:53\ngithub.com/mattermost/mattermost-server/app.(*App).UpdateConfig\n\t/go/src/github.com/mattermost/mattermost-server/app/config.go:59\ngithub.com/mattermost/mattermost-server/app.(*App).EnablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/app/plugin.go:245\ngithub.com/mattermost/mattermost-server/api4.enablePlugin\n\t/go/src/github.com/mattermost/mattermost-server/api4/plugin.go:187\ngithub.com/mattermost/mattermost-server/web.Handler.ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/web/handlers.go:167\ngithub.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/src/github.com/mattermost/mattermost-server/vendor/github.com/gorilla/mux/mux.go:162\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"}

**Environment (if applicable):**
-  OS: Linux Docker

**Comment by harshilsharma** [comment] 2019-05-20 14:21
@poVoq Thanks for reporting the bug!

This seems to be a duplicate of #14 and is actually a bug in Mattermost docker itself, due to lack of tz data. The fix of this is released with Mattermost-Docker version 5.11.

I'd suggest updating Mattermost-Docker to the latest version. If that's not possible, maybe you can apply the patch (https://github.com/mattermost/mattermost-docker/pull/390) to your current Mattermost-Docker image.

**Comment by harshilsharma** [comment] 2019-05-20 14:22
Let me know if that fixes your issue.

**Comment by poVoq** [comment] 2019-05-20 14:52
I am already on 5.11 but updated from 5.10. The issue persists. Anything I might have overlooked when updating?

**Comment by harshilsharma63** [comment] 2019-05-20 14:57
I haven't used Mattermost-Docker much, but I'll try running the plugin in it to see if I get the error.

What's your host OS BTW? Can you try running this Go code in your base OS to see which timezones does it have - https://github.com/standup-raven/standup-raven/issues/14#issuecomment-488692888 ?

**Comment by harshilsharma** [comment] 2019-05-20 14:57
I haven't used Mattermost-Docker much, but I'll try running the plugin in it to see if I get the error.

What's your host OS BTW? Can you try running this Go code in your base OS to see which timezones does it have - https://github.com/standup-raven/standup-raven/issues/14#issuecomment-488692888 ?

**Comment by poVoq** [comment] 2019-05-21 00:27
My host OS is Ubuntu18.04 but I really only use it as a Docker host and do not have Go etc installed.

I checked all the issues and also the new Mattermost 5.11 Docker deployment guide, but I can't figure out what I did substantially different.

Maybe I'll do a clean installation again will all new volumes / database etc. to see if that helps.

**Comment by skame** [comment] 2019-05-21 15:35
I met the 'unknown timezone' problem before https://github.com/mattermost/mattermost-docker/pull/390 merged, mattermost/mattermost-prod-app:5.10.0.

After the patch merged :latest and mattermost/mattermost-prod-app:5.11.0 I have no problem in timezone Asia/Tokyo.

**Comment by poVoq** [comment] 2019-05-28 17:11
Maybe this is a MySQL issue? I completely reinstalled with a fresh database and new docker volumes from the official 5.11 Docker image and I am still not able to start this plugin.

**Comment by poVoq** [comment] 2019-06-27 16:34
Yes apparently no change with version 1.4.0. and the latest Mattermost Team Edition.

**Comment by harshilsharma63** [comment] 2019-06-27 23:42
@poVoq I see. Are you able to change timezone for Mattermost? You'll need to go to `System Console` > `Experimental` > `Timezone` and set it to `true`. Then in your `Account Settings` go to `Display` and try changing the timezone. If that works for you, I can try looking into how Mattermost implements timezones and compare it with the implementation we have here.

**Comment by poVoq** [comment] 2019-06-28 05:20
Yes changing time-zone works. Thanks for looking into it.

**Closed** 2019-07-14 23:47 UTC
Labels: duplicate
