### ISSUE TITLE
BUG - unknown time zone

### ISSUE THREAD

**Issue by tgly307** [standup-raven/standup-raven#14] opened 2019-04-29 17:12 UTC
**Summary**
I set the time zone Asia/Shanghai in plugin, and the log throw error "config unknown time zone"

`{"level":"error","ts":1556557748.1725073,"caller":"mlog/sugar.go:23","msg":"unknown time zone Asia/Shanghai","plugin_id":"standup-raven"}`

I also tried some other time zone, all failed without UTC.

**Steps To Reproduce**
1. install plugin
2. modify the plugin config 
3. See error

**Expected behavior**
What you expected to happen.

**Observed Behavior**
What actually happened.

**Screenshots**

**Environment (if applicable):**
-  OS: windows 10 desktop app 4.2.0

**Comment by tgly307** [comment] 2019-04-30 02:10
I found a temporary solution, I added a line in time zone of settings_schema in plugin.json to set the time zone.
 `{"display_name": "Local", "value": "Local"},`
I guess this problem may be caused by a dependency package.

**Comment by harshilsharma** [comment] 2019-04-30 03:18
@tgly307 big thanks for the bug report!

I did a quick try but I'm not getting this error. Will try it out again with a clean setup.

**Comment by harshilsharma** [comment] 2019-04-30 03:18
BTW which version of Mattermost are you using?

**Comment by tgly307** [comment] 2019-04-30 04:07
My mattermost version is 5.10.0, run by [docker-compose](https://github.com/mattermost/mattermost-docker). I build the image by myself and run `docker-compose up`, maybe the issue is related with the build part? My OS is centOS7 64bit.

**Comment by hubpav** [comment] 2019-05-02 06:53
I have the same issue - `Europe/Prague` is reported as unknown time zone. Mattermost version `5.9.0` through Docker Compose deployment.

**Comment by harshilsharma** [comment] 2019-05-02 14:22
@tgly307 @hubpav can you try running this code from StackOverflow answer - https://stackoverflow.com/a/40130882/1589165

Inserting code here for quick reference -

```go
package main

import (
	"fmt"
	"io/ioutil"
	"strings"
)

var zoneDirs = []string{
	// Update path according to your OS
	"/usr/share/zoneinfo/",
	"/usr/share/lib/zoneinfo/",
	"/usr/lib/locale/TZ/",
}

var zoneDir string

func main() {
	for _, zoneDir = range zoneDirs {
		ReadFile("")
	}
}

func ReadFile(path string) {
	files, _ := ioutil.ReadDir(zoneDir + path)
	for _, f := range files {
		if f.Name() != strings.ToUpper(f.Name()[:1]) + f.Name()[1:] {
			continue
		}
		if f.IsDir() {
			ReadFile(path + "/" + f.Name())
		} else {
			fmt.Println((path + "/" + f.Name())[1:])
		}
	}
}

```

This will generate a list of timezone strings available for your system. I suspect this is something system-specific.

It would be helpful if you could tell which OS are you on.

**Comment by tgly307** [comment] 2019-05-02 16:31
@harshilsharma I guess the problem is on the alpine image, because the image is based on the alpine image. It is estimated that the time zone setting here is different from that of centOS. I enable the official experimental feature `ExperimentalTimezone`, then I chose automatic in user profile setting, the time zone is displayed as `Shanghai` instead of `Asia/Shanghai`

**Comment by harshilsharma** [comment] 2019-05-03 00:20
@tgly307 good point! I didn't realize that. I compiled the timezone list on MacOS but they run fine for me, even though I'm also running local Mattermost via docker-compose.

**Comment by harshilsharma** [comment] 2019-05-03 00:22
Let me correct that, I'm not running Mattermost via docker, but directly via the `make run` command from the source code. I'll test with MM docker as well.

**Comment by harshilsharma** [comment] 2019-05-03 00:58
I'm able to reproduce error on docker-compose version of Mattermost.

**Comment by harshilsharma** [comment] 2019-05-03 01:08
I'm able to reproduce it on docker version of Mattermost. We have a copy of this plugin running on Ubuntu and the timezones work fine with it. Like you mentioned, it seems to be an issue with Alpine managing timezones.

**Comment by harshilsharma** [comment] 2019-05-03 01:09
@tgly307  @hubpav would it be possible for you to install the compiled version of Mattermost to try with?

**Comment by tgly307** [comment] 2019-05-05 16:12
What is compiled version? The docker image is built with the package after compiled. Do you mean this?

**Comment by scottleedavis** [comment] 2019-05-05 18:59
PR just merged in mattermost-docker likely solved this problem.

**Comment by tgly307** [comment] 2019-05-06 01:34
@harshilsharma hi, by PR of @scottleedavis ,the problem is solved, the time zone can be set to other one. The issue can be close if you want. Thanks for the work.

**Comment by hubpav** [comment] 2019-05-07 06:13
👍

**Comment by harshilsharma** [comment] 2019-05-11 05:13
@scottleedavis thanks for the docker fix!

Referring the PR here for reference - https://github.com/mattermost/mattermost-docker/pull/390

**Closed by harshilsharma** 2019-05-11 05:13 UTC
Labels: bug, in-progress, server
